### ISSUE TITLE
Input.emit doesn`t work when you apply theme

### ISSUE THREAD

**Issue by Nawarius** [fltk-rs/fltk-theme#4]
Hey fltk team! Thanks for the great GUI libraries!

You have this function in your library in `src\widget_themes\mod.rs`
```
pub(crate) fn use_native_settings() {
    app::set_visible_focus(false);
    app::set_scrollbar_size(15);
    Tooltip::set_font_size(OS_FONT_SIZE);
    Tooltip::set_delay(0.5);
}
```  
Because of this line `app::set_visible_focus(false);` my code below is not working. 
To fix this, I have to use `app::set_visible_focus(true);` after `widget_theme.apply();` in code below.
```
use fltk::{prelude::*, *};
use fltk_theme::{widget_themes, WidgetTheme, ThemeType};
#[derive(Copy, Clone)]
enum TaskMessage {
    Done
}

fn main () {
    let a = app::App::default();
    let (sender, receiver) = app::channel();

    let widget_theme = WidgetTheme::new(ThemeType::Dark);
    widget_theme.apply();
    
    let mut win = window::Window::default().with_size(400, 300);
    let mut btn = button::Button::new(160, 200, 80, 30, "Hello");
    btn.set_frame(widget_themes::OS_DEFAULT_BUTTON_UP_BOX);
    btn.emit(sender, TaskMessage::Done);

    let mut add_input = input::Input::default().with_size(200, 30);
    add_input.emit(sender, TaskMessage::Done);

    win.end();
    win.show();

    while a.wait() {
        if let Some(msg) = receiver.recv() {
            match msg {
                TaskMessage::Done => {
                    println!("Here")
                }
            }
        }
    }
    a.run().unwrap();
}
```

Excuse me for my impudence, but in order to find this, I had to look at the library code. I think that changing the theme of the application should not affect the state management

**Comment by MoAlyousef** [comment]
Hi
Lack of focus on inputs seems to disable their EnterKey trigger, you can try adding:
`add_input.set_trigger(enums::CallbackTrigger::EnterKey);` 
This also avoids having visible_focus on all other widgets which might not be desirable from a UI perspective.

**Comment by Nawarius** [comment]
This correctly solves the problem. Thank you for your reply!
