### ISSUE TITLE
How can I edit and modify the color values of a theme? Is there any way to know the corresponding position of these indexed colors

### ISSUE THREAD

**Issue by kihlh** [fltk-rs/fltk-theme#8]
Thank you very much for your work "fltk-theme". It is really great and gives the fltk framework a beautiful appearance. However, I hope to be able to customize the theme and allow users to dynamically adjust it. This requires understanding which colors correspond to these indices and where they will appear. Previously, I searched for them by their color values, but this method was difficult.

![image](https://github.com/fltk-rs/fltk-theme/assets/62889891/766c90f9-85dd-4f35-ad92-a9c2cd2b690b)

![654638544](https://github.com/fltk-rs/fltk-theme/assets/62889891/5427d16e-e279-4ef6-8046-9bcb0e2f8699)

**Comment by MoAlyousef** [comment]
Hello

So the corresponding index can be found here:
https://www.fltk.org/doc-1.4/fltk-colormap.png

The cmap macro just basically calls `Fl::set_color(index, r, g, b)` or in fltk-rs terms `app::set_color(Color::by_index(index), r, g, b)`, however some of the colors are automatic, like when setting the background color, this will also change the gray ramp. and how deactivated widgets would appear.

See also the [dynamic.rs](https://github.com/fltk-rs/fltk-theme/blob/main/examples/dynamic.rs) example, which loads map files from examples/themes (where you can find some comments as well).

You can also try experimenting without fltk-theme:
```rust
    app::set_color(Color::Background, 0x21, 0x25, 0x2b);
    app::set_color(Color::Background2, 0x28, 0x2c, 0x34);
    app::set_color(Color::Foreground, 0xab, 0xb2, 0xa2);
    app::set_color(Color::Selection, 0x32, 0x38, 0x42);
    app::set_color(Color::Inactive, 88, 0, 0);
    app::set_color(Color::by_index(some_index), r, g, b); // fill rgb values
```

The themes were taken from https://groups.google.com/g/fltkgeneral/c/3A5VC_854ok/m/uFhew6WJBAAJ, so you might be able to get more information from there.
