### ISSUE TITLE
Question: is it possible to revert to the "default" theme after applying a theme?

### ISSUE THREAD

**Issue by dheijl** [fltk-rs/fltk-theme#9]
without restarting the application?

**Comment by MoAlyousef** [comment]
It should be possible. I’ll try to implement it tomorrow. 
FLTK creates the colormap on initialization and exposes it as a global. fltk-theme could store the default colormap, and provide a reload_theme function which restores it.

**Comment by MoAlyousef** [comment]
I have added:
```rust
fltk_theme::reset_color_map();
```
in version 0.7.3

**Comment by dheijl** [comment]
Thank you very much! I'll try it out asap.

**Comment by dheijl** [comment]
Thanks again, problem solved!
